global:
    smtp_smarthost: 'mailpit:1025'
    smtp_from: 'alertas@medschedule.local'
    smtp_require_tls: false

route:
    receiver: correo-equipo
    group_by: [alertname]
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 1h

receivers:
    - name: correo-equipo
      email_configs:
          - to: 'equipo@medschedule.local'
            send_resolved: true
